export const eventsSeed = [
  {
    id: "1",
    name: "Future of AI Summit",
    organizer: "TechPulse",
    location: "San Francisco, CA",
    date: new Date("2026-12-15T09:00:00Z"),
    description:
      "Explore the cutting edge of artificial intelligence with world-class speakers and hands-on workshops.",
    capacity: 500,
    availableSeats: 500,
    category: "TECH",
    imageUrl:"https://picsum.photos/seed/tech1/800/400",
    price: 299,
  },
  {
    id: "2",
    name: "Midnight Jazz Sessions",
    organizer: "Blue Note Collective",
    location: "New Orleans, LA",
    date: new Date("2026-11-20T21:00:00Z"),
    description:
      "An intimate evening of soulful jazz featuring local legends and rising stars.",
    capacity: 100,
    availableSeats: 0, // Sold out event for testing
    category: "MUSIC",
    imageUrl:"https://picsum.photos/seed/music1/800/400",
    price: 45,
  },
  {
    id: "3",
    name: "Modern Art Expo 2026",
    organizer: "Visionary Gallery",
    location: "New York, NY",
    date: new Date("2027-01-10T10:00:00Z"),
    description:
      "Discover the next generation of visual artists in this expansive multi-media exhibition.",
    capacity: 1000,
    availableSeats: 1000,
    category: "ART",
    imageUrl: "https://picsum.photos/seed/art1/800/400",
    price: 25,
  },
  {
    id: "4",
    name: "Global Business Forum",
    organizer: "Enterprise World",
    location: "London, UK",
    date: new Date("2027-03-05T08:30:00Z"),
    description:
      "Networking and insights for the modern entrepreneur in a changing global economy.",
    capacity: 300,
    availableSeats: 300,
    category: "BUSINESS",
    imageUrl:"https://picsum.photos/seed/biz1/800/400",
    price: 550,
  },
  {
    id: "5",
    name: "Gourmet Food Festival",
    organizer: "Taste of City",
    location: "Austin, TX",
    date: new Date("2026-11-28T12:00:00Z"),
    description:
      "A weekend of culinary delights, featuring celebrity chefs and local food trucks.",
    capacity: 2000,
    availableSeats: 2000,
    category: "FOOD",
    imageUrl:"https://picsum.photos/seed/food1/800/400",
    price: 15,
  },
  {
    id: "6",
    name: "Extreme Sports Weekend",
    organizer: "Adrenaline Rush",
    location: "Denver, CO",
    date: new Date("2027-05-15T09:00:00Z"),
    description:
      "Biking, climbing, and skating competitions in the heart of the Rockies.",
    capacity: 500,
    availableSeats: 500,
    category: "SPORTS",
    imageUrl:"https://picsum.photos/seed/sports1/800/400",
    price: 0, // Free event
  },
  {
    id: "7",
    name: "Cloud Infrastructure Workshop",
    organizer: "DevOps Weekly",
    location: "Seattle, WA",
    date: new Date("2026-12-05T13:00:00Z"),
    description:
      "Master AWS, Azure, and GCP in this intensive 3-day deep dive.",
    capacity: 50,
    availableSeats: 50,
    category: "TECH",
    imageUrl:"https://picsum.photos/seed/tech2/800/400",
    price: 899,
  },
  {
    id: "8",
    name: "Sunset Symphony",
    organizer: "City Orchestra",
    location: "Chicago, IL",
    date: new Date("2026-12-12T18:30:00Z"),
    description:
      "Classical masterpieces performed under the stars at Millennium Park.",
    capacity: 5000,
    availableSeats: 5000,
    category: "MUSIC",
    imageUrl: "https://picsum.photos/seed/music2/800/400",
    price: 0,
  },
];
